[tmux.files]
"tmux.conf" = {target = "~/.tmux.conf", type = "template", append = "set-option -sa terminal-overrides ',alacritty:RGB'"}

[zsh.files.zshrc]
target = "~/.zshrc"
type = "template"
append = """
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
"""
