[tmux.files]
"tmux.conf" = {target = "~/.tmux.conf", type = "template", append = "set-option -sa terminal-overrides ',xterm-256color:RGB'"}

[zsh.files.zshrc]
target = "~/.zshrc"
type = "template"
append = """
alias ls="/usr/local/opt/coreutils/libexec/gnubin/ls"
"""
